version: '3.8'

services:
  app:
    build: .
    container_name: go-toronto-time-app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - DB_USER=root
      - DB_PASSWORD=1qw
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=time_logger
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: mysql-server
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=1qw
      - MYSQL_DATABASE=time_logger
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
